# Usa uma imagem base do Node.js
FROM node:22

# Define o diretório de trabalho no container
WORKDIR /app

# Copia package.json e o pnpm-lock.yaml
# Caso estive usando o npm, o COPY deveria ser:
# COPY package*.json ./
COPY package.json pnpm-lock.yaml ./

# Instala as dependências
RUN npm install -g pnpm && pnpm install

# Copia todos os arquivos que tem na máquina local pra dentro do WORKDIR
COPY . .

# Expõe a porta do servidor de desenvolvimento
EXPOSE 5173

# Inicia o servidor de desenvolvimento
CMD ["pnpm", "run", "dev", "--host"]